Repository stolostron/cluster-backup-operator, pull requests merged in 2021-08, with the labels that each got.

#11 test checkin
  README.md
Labels: approved

#15 Activate short test
  Makefile.prow
Labels: approved, lgtm

#14 Adding unit tests for backup utility functions
  controllers/backup_test.go
Labels: approved, lgtm

#18 Add signed reference to contribution md
  CONTRIBUTING.md
  sonar-project.properties
Labels: approved, lgtm, dco-signoff: yes

#19 to fix operator-sdk issue
  PROJECT
Labels: approved, lgtm, dco-signoff: yes

#20 implement multiple files backup
  CONTRIBUTING.md
  README.md
  api/v1beta1/backup_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/backup.cluster.management.io_backups.yaml
  config/crd/bases/backup.cluster.management.io_restores.yaml
  config/crd/bases/cluster.open-cluster-management.io_backups.yaml
  config/samples/cluster_v1beta1_backup.yaml
  controllers/backup.go
  controllers/backup_controller.go
  controllers/backup_controller_test.go
  controllers/backup_test.go
  controllers/restore_test.go
  controllers/utils.go
Labels: approved, lgtm, dco-signoff: yes

#22 move GH domain to open-cluster-management/
  controllers/backup.go
  controllers/backup_controller.go
  controllers/backup_controller_test.go
  controllers/backup_test.go
  controllers/restore.go
  controllers/restore_controller.go
  controllers/restore_controller_test.go
  controllers/restore_test.go
  controllers/suite_test.go
  controllers/utils.go
  go.mod
  main.go
Labels: approved, lgtm, dco-signoff: yes
