Repository stolostron/cluster-backup-operator, pull requests merged in 2021-09, with the labels that each got.

#23 update readme with execution details
  README.md
Labels: approved, lgtm, dco-signoff: yes

#25 create watch rules for channel and managedcluster crd
  config/rbac/role.yaml
  controllers/backup.go
  controllers/backup_controller.go
Labels: approved, lgtm, dco-signoff: yes

#26 Fix sonar issues
  controllers/backup.go
  controllers/backup_controller.go
  controllers/schedule_controller.go
  main.go
Labels: approved, lgtm, dco-signoff: yes

#27 rebuild
  rebuild.md
Labels: approved, lgtm, dco-signoff: yes

#28 update roles for deletebackuprequests
  config/rbac/role.yaml
  controllers/backup_controller.go
Labels: approved, lgtm, dco-signoff: yes

#29 update COMPONENT NAME & VERSION
  COMPONENT_NAME
  COMPONENT_VERSION
Labels: approved, lgtm, dco-signoff: yes

#31 rebuild
  rebuild.md
Labels: approved, lgtm, dco-signoff: yes

#32 rebuild
  rebuild.md
Labels: approved, lgtm, dco-signoff: yes

#30 remove VeleroConfigBackupProxy
  README.md
  api/v1beta1/backup_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cluster.open-cluster-management.io_backups.yaml
  config/samples/cluster_v1beta1_backup.yaml
  controllers/backup.go
  controllers/backup_controller.go
  controllers/backup_controller_test.go
  controllers/backup_test.go
  controllers/schedule_controller.go
Labels: approved, lgtm, dco-signoff: yes

#34 make backups TTL optional
  api/v1beta1/schedule_types.go
  config/crd/bases/cluster.open-cluster-management.io_backupschedules.yaml
  config/samples/cluster_v1beta1_backupschedule.yaml
  controllers/schedule_controller_test.go
Labels: approved, lgtm, dco-signoff: yes

#35 add maxBackups to backupschedule operator
  README.md
  api/v1beta1/schedule_types.go
  config/crd/bases/cluster.open-cluster-management.io_backupschedules.yaml
  config/samples/cluster_v1beta1_backupschedule.yaml
  controllers/backup.go
  controllers/backup_controller.go
  controllers/schedule_controller.go
  controllers/schedule_controller_test.go
Labels: approved, lgtm, dco-signoff: yes

#36 Validate cron job schedule and set phase and message
  api/v1beta1/schedule_types.go
  config/crd/bases/cluster.open-cluster-management.io_backupschedules.yaml
  controllers/schedule.go
  controllers/schedule_controller.go
  go.mod
  go.sum
Labels: approved, dco-signoff: yes

#17 To revamp restore controller
  README.md
  api/v1beta1/restore_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cluster.open-cluster-management.io_restores.yaml
  config/crd/bases/infrastructures_config_openshift_io.crd.yaml
  config/rbac/role.yaml
  config/samples/cluster_v1beta1_restore.yaml
  controllers/restore.go
  controllers/restore_controller.go
  controllers/restore_controller_test.go
  controllers/restore_test.go
  controllers/suite_test.go
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, do-not-merge/hold

#37 errata to previous commit
  README.md
  config/rbac/role.yaml
  controllers/restore_controller.go
Labels: approved, lgtm, dco-signoff: yes

#38 fix some minor readme issues
  README.md
  images/cluster-backup-controller-dataflow.png
Labels: approved, lgtm, dco-signoff: yes

#39 add debug details when schedule has no status
  controllers/schedule.go
Labels: approved, lgtm, dco-signoff: yes

#41 don't create backup schedule if storage location is not available
  controllers/schedule_controller.go
Labels: approved, lgtm, dco-signoff: yes

#40 Restore controller fixes.
  api/v1beta1/restore_types.go
  config/crd/bases/cluster.open-cluster-management.io_restores.yaml
  config/rbac/role.yaml
  controllers/restore.go
  controllers/restore_controller.go
  controllers/schedule_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, dco-signoff: yes

#43 remove backup controller, replaced by the schedule controller
  api/v1beta1/backup_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/rbac/role.yaml
  config/samples/cluster_v1beta1_backup.yaml
  config/samples/kustomization.yaml
  controllers/backup.go
  controllers/backup_controller.go
  controllers/backup_controller_test.go
  controllers/backup_test.go
  controllers/schedule_controller.go
  controllers/suite_test.go
  controllers/utils.go
  main.go
Labels: approved, lgtm, dco-signoff: yes

#42 Support schedule edit
  config/rbac/role.yaml
  controllers/schedule.go
  controllers/schedule_controller.go
Labels: approved, dco-signoff: yes

#44 fix sonar vulnerabilities
  controllers/restore.go
  controllers/restore_controller.go
Labels: approved, lgtm, dco-signoff: yes

#46 restore controller crash if admin secret not found
  config/crd/bases/cluster.open-cluster-management.io_backups.yaml
  config/crd/kustomization.yaml
  controllers/restore_controller.go
Labels: approved, lgtm, dco-signoff: yes

#47 Fixing an rbac and some sonar issues
  controllers/schedule_controller.go
Labels: approved, lgtm, dco-signoff: yes

#48 Add Velero crds to be installed by this operator
  config/crd/bases/velero.io_backupstoragelocations.yaml
  config/crd/bases/velero.io_deletebackuprequests.yaml
  config/crd/bases/velero.io_restores.yaml
  config/crd/bases/velero.io_schedules.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  controllers/schedule_controller.go
Labels: approved, lgtm, dco-signoff: yes

#50 Update restore controller to restore all backup types
  api/v1beta1/restore_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cluster.open-cluster-management.io_restores.yaml
  controllers/backup_test.go
  controllers/restore.go
  controllers/restore_controller.go
  controllers/restore_controller_test.go
  controllers/schedule.go
  controllers/schedule_controller.go
  controllers/utils.go
Labels: approved, lgtm, dco-signoff: yes

#51 add managed clusters obj to backup
  controllers/backup.go
  controllers/schedule_controller.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, dco-signoff: yes

#52 fix typo on argocd res names
  controllers/backup.go
Labels: approved, lgtm, dco-signoff: yes

#53 to get rid of post-processing while restoring
  config/rbac/role.yaml
  controllers/restore.go
  controllers/restore_controller.go
  controllers/restore_controller_test.go
  controllers/restore_test.go
Labels: approved, lgtm, dco-signoff: yes

#54 Update restore API, Add tests
  api/v1beta1/restore_types.go
  config/crd/bases/cluster.open-cluster-management.io_restores.yaml
  config/samples/cluster_v1beta1_restore.yaml
  controllers/restore_controller.go
  controllers/restore_controller_test.go
Labels: approved, lgtm, dco-signoff: yes

#55 update readme for restore and backup details
  README.md
Labels: approved, lgtm, dco-signoff: yes

#56 check velero status before restore, fix sonar, fix tests
  api/v1beta1/restore_types.go
  controllers/restore_controller.go
  controllers/restore_controller_test.go
  controllers/schedule_controller_test.go
Labels: approved, lgtm, dco-signoff: yes

#57 to add schedule tests
  controllers/schedule_test.go
Labels: approved, lgtm, dco-signoff: yes

#58 check only existing backups created by the acm schedule
  api/v1beta1/restore_types.go
  config/crd/bases/cluster.open-cluster-management.io_restores.yaml
  controllers/backup.go
  controllers/schedule_controller.go
Labels: approved, lgtm, dco-signoff: yes

#59 add cluster pools role
  config/rbac/role.yaml
  controllers/schedule_controller.go
Labels: approved, lgtm, dco-signoff: yes

#60 restore op can be executed once
  README.md
Labels: approved, lgtm, dco-signoff: yes

#61 update readme for restore file types
  README.md
Labels: approved, lgtm, dco-signoff: yes

#62 update oadp install link
  README.md
Labels: approved, lgtm, dco-signoff: yes

#63 update ttl description
  api/v1beta1/schedule_types.go
  config/crd/bases/cluster.open-cluster-management.io_backupschedules.yaml
  config/samples/cluster_v1beta1_backupschedule.yaml
Labels: approved, lgtm, dco-signoff: yes

#64 check if restore resource is in the velero ns
  controllers/restore_controller.go
  controllers/restore_controller_test.go
  controllers/schedule_controller.go
Labels: approved, lgtm, dco-signoff: yes

#65 create valid k8s name and add tests
  controllers/backup_test.go
  controllers/restore_controller.go
  controllers/restore_controller_test.go
  controllers/schedule_controller_test.go
  controllers/utils.go
Labels: approved, lgtm, dco-signoff: yes
